problem1: problem1.c
	gcc -o problem1 problem1.c -g

problem2: problem2.c
	gcc -o problem2 problem2.c -g

problem3: problem3.c
	gcc -o problem3 problem3.c -lpthread -g

problem4: problem4.c
	gcc -o problem4 problem4.c -lpthread -g

